title: Investment Analytics
description: An experimental project for investment and retirement data analytics.
# Author will be used in meta tags and page footers
# author:
#   name: mikejonestechno

# c6e74bbfe7a0d0ae8c806cb38b012d01b25b1f7d release 2.5.2 (does not support skin: dark)
# 1e8a445e8fd7280d0fd9d448c0f71c93a2565837 28 Feb 2025 (before 'improve navigation styling and experience')
remote_theme: jekyll/minima@1e8a445e8fd7280d0fd9d448c0f71c93a2565837

plugins:
  - jekyll-seo-tag
  # minima theme was designed with jekyll-feed to create rss feed of blog posts
  #- jekyll-feed
  - jekyll-remote-theme
  # NOTE: add custom _includes/footer.html to remove the rss 'subscribe' link
  - jekyll-redirect-from
  
header_pages:
  - retirement-planning.md
  - inflation-and-interest-rates.md
  - investing.md

# kramdown adds support for markdown extensions like 'notice' blocks.
kramdown:
  parse_block_html: true

content:
  footer: |
    ⚠ **Disclaimer**: _Not financial advice_. All content is for educational purposes only. 
    No warranty or guarantee or forward looking statements of fit for purpose, etc;     
    do your own research.

minima:
  skin: dark
  date_format: "%d %b %Y"
  social_links:
    - { platform: x, user_url: "https://x.com/mikejonestechno" }
    - { platform: github, user_url: "https://github.com/mikejonestechno" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/mikejonestechno/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@MikeJonesTechno" }
    - { platform: wordpress, user_url: "https://mikejonestechno.wordpress.com/" }
