title: Investment Analytics
description: An experimental project for investment and retirement data analytics.
#theme: jekyll-theme-primer
theme: minima

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/mikejonestechno" }
