title: Investment Analytics
description: An experimental project for investment and retirement data analytics.
#theme: jekyll-theme-primer
theme: jekyll-theme-minima
#remote_theme: pages-themes/minima@v0.2.0
#plugins:
#- jekyll-remote-theme
#show_downloads: false
