title: Investment Analytics
description: An experimental project for investment and retirement data analytics.
author:
  name: mikejonestechno

#theme: jekyll-theme-primer
#theme: minima
remote_theme: jekyll/minima

plugins:
  - jekyll-seo-tag
  #- jekyll-feed
  # NOTE: add custom _includes/footer.html to remove the rss 'subscribe' link
  
header_pages:
  - retirement-planning.md

minima:
  skin: dark
  date_format: "%d %b %Y"
  social_links:
    - { platform: github, user_url: "https://github.com/mikejonestechno" }
