title: Investment Analytics
description: An experimental project for investment and retirement data analytics.
#theme: jekyll-theme-minimal # try slate theme?
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false
