name: Run Jupyter Notebooks

on:
  #schedule:
    # Runs at 21:00 UTC every day
    # - cron:  '0 21 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install notebook
        pip install nbconvert

    - name: Convert notebooks to Markdown
      run: |
        for notebook in notebooks/*.ipynb; do
          jupyter nbconvert --to markdown "$notebook" --output-dir="./pages/notebooks" --debug
        done        