name: Run Jupyter Notebooks

on:
  #schedule:
    # Runs at 21:00 UTC every day
    # - cron:  '0 21 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install jekyllnb

    - name: Convert notebooks to Markdown
      run: jupyter jekyllnb --site-dir pages --page-dir pages/_pages --image-dir _pages/images --no-auto-folder notebooks/inflation.ipynb
      #run: jupyter nbconvert --to=markdown --output-dir="./pages/notebooks" --debug notebooks/inflation.ipynb        
        # for notebook in notebooks/inflation.ipynb; do
        #  jupyter nbconvert --to=markdown --output-dir="./pages/notebooks" --debug "$notebook"
        # done        

    - name: Upload for Debugging
      uses: actions/upload-artifact@v4
      with:
        name: notebooks
        path: pages