name: Run Jupyter Notebooks

on:
  #schedule:
    # Runs at 21:00 UTC every day
    # - cron:  '0 21 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry Run'
        required: false
        default: 'true'

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install jekyllnb

    - name: Notebooks to Jekyl Markdown
      run: jupyter jekyllnb --site-dir pages --page-dir _pages --image-dir _pages/images --no-auto-folder notebooks/spx-and-tsla.ipynb
      #run: jupyter nbconvert --to=markdown --output-dir="./pages/notebooks" --debug notebooks/inflation.ipynb        
        # for notebook in notebooks/inflation.ipynb; do
        #  jupyter nbconvert --to=markdown --output-dir="./pages/notebooks" --debug "$notebook"
        # done        

    - name: Upload for Debugging
      uses: actions/upload-artifact@v4
      with:
        name: notebooks
        path: pages

    # this action was designed to push commits to the gh-pages branch which would then be served by GitHub Pages
    # i want to push the files in pages to the main branch to trigger the GitHub Pages deployment
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: main
        folder: pages
        dry-run: ${{ github.event.inputs.dry-run }}
