name: Publish Jupyter Notebooks

on:
  #schedule:
    # Runs at 21:00 UTC every day
    # - cron:  '0 21 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry Run'
        type: boolean
        required: false
        default: true
permissions:
  contents: write    

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install jekyllnb

    - name: Notebooks to Jekyl Markdown
      # Dont put pages in subdir because jekllnb hardcoded permalink to "/"
      # Unless we add a custom jekyll json to each notebook
      run: jupyter jekyllnb --site-dir pages --page-dir notebooks --image-dir images --no-auto-folder notebooks/spx-and-tsla.ipynb
      # Perhaps I can just use nbconvert with first markdown cell contains the frontmatter

    - name: Commit changes
      uses: actions-x/commit@v6        

